### ISSUE TITLE
Can't upload a file

### ISSUE THREAD

**Issue by Will695** [michaelnew/Octoprint-Print-Queue#2]
Hi,

How do i use this, I can't seem to upload a file in the print queue

**Comment by michaelnew** [comment]
Sorry, I need to update the documentation. Just select a file using Octoprint's file browser, then open the plugin tab and hit the `+` button.

Also, just a reminder, this plugin is very experimental and mostly just used by me at this point. So be careful.

**Comment by Will695** [comment]
Thanks, This is exactly what i was looking for. Saves me messing about with Polar3d's queue. 
The box to the right of the file when you add it, is that a "print in this order" thing or is that how many copies of the print you want to do ?

**Comment by michaelnew** [comment]
It’s a “print this number of copies” box. I guess I should make that more clear as well.

**Comment by Will695** [comment]
So awesome! it's working pretty well so far, thank you for writing it!

**Comment by michaelnew** [comment]
I added some labels, help bubbles, and so on to hopefully make this more clear in the future. Going to go ahead and close this.
